"""Change column status in Tickets table

Revision ID: 561e2d04f28c
Revises: 6cea6cd09c0f
Create Date: 2023-11-26 22:37:55.538893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561e2d04f28c'
down_revision: Union[str, None] = '6cea6cd09c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
