"""Add text column in message table

Revision ID: 9f3ca73717f6
Revises: 485041c1e5b6
Create Date: 2023-11-26 21:31:29.375796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3ca73717f6'
down_revision: Union[str, None] = '485041c1e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'text')
    # ### end Alembic commands ###
